"""empty message

Revision ID: 26f19d50b675
Revises: 8b3c90e2fa1e
Create Date: 2023-12-20 14:28:01.604317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26f19d50b675'
down_revision = '8b3c90e2fa1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('msg',
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=126), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('msg', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_msg_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('msg', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_msg_timestamp'))

    op.drop_table('msg')
    # ### end Alembic commands ###
