"""empty message

Revision ID: e0318901d228
Revises: cdb4945185b5
Create Date: 2023-12-22 23:51:45.084511

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'e0318901d228'
down_revision = 'cdb4945185b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sqlite.JSON(), nullable=False))

    # ### end Alembic commands ###
