name: Deploy to Google App Engine

on:
  push:
    branches:
      - main

env:
  key: '${{ secrets.key }}'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to AWS EC2 Instance
      run: |
        bash deploy.sh
        echo "Deploy Success"